######################################################################
# Automatically generated by qmake (3.0) Sat Feb 14 16:05:34 2015
######################################################################

TEMPLATE = app
TARGET = logger
INCLUDEPATH += .
QT = core
CONFIG += debug c++14

# Input
HEADERS += logger.h
SOURCES += logger.cpp main.cpp
